name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  debpoy:

    runs-on: bb-galaxy-questionnaire

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run docker:build 
    - run: docker rm -f questionnaire | true
    - run: docker run --restart=unless-stopped -d -p 2201:2200 --network mongo --name questionnaire bb-galaxy-questionnaire


